services:
    frontend:
        container_name: app_frontend
        build: ./frontend
        ports:
          - 3000:3000
        platform: linux/x86_64
        working_dir: /frontend
        volumes: 
          - ./frontend:/frontend
          - ./:/react-docker:delegated
          - /node_modules
        depends_on:
          backend:
            condition: service_healthy
        healthcheck:
          test: ["CMD", "lsof", "-t", "-i:3000"]
          timeout: 10s
          retries: 5
        environment:
          - CHOKIDAR_USEPOLLING=true
          - NODE_ENV=production
    backend:
        container_name: app_backend
        build: ./backend
        ports:
          - 3001:3001
        platform: linux/x86_64
        working_dir: /backend
        volumes: 
          - ./backend:/backend
        environment:
          - APP_PORT=3001
          - THING_PASSWORD=s1e2r3i4o5u6s7
          - OPENAI_ORG=org-DUp3EHv0fsQo7k3BMgxtH906
          - OPENAI_API_KEY=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
        healthcheck:
          test: ["CMD", "lsof", "-t", "-i:3001"]
          timeout: 10s
          retries: 5