services:
    frontend:
        container_name: app_frontend
        build: ./frontend
        ports:
          - 3000:3000
        platform: linux/x86_64
        working_dir: /frontend
        volumes: 
          - ./frontend:/frontend
          - ./:/react-docker:delegated
          - /node_modules
        depends_on:
          backend:
            condition: service_healthy
        healthcheck:
          test: ["CMD", "lsof", "-t", "-i:3000"]
          timeout: 10s
          retries: 5
        environment:
          - CHOKIDAR_USEPOLLING=true
    backend:
        container_name: app_backend
        build: ./backend
        ports:
          - 3001:3001
        platform: linux/x86_64
        working_dir: /backend
        volumes: 
          - ./backend:/backend
        environment:
          - APP_PORT=3001
        depends_on:
          db:
            condition: service_healthy
        healthcheck:
          test: ["CMD", "lsof", "-t", "-i:3001"]
          timeout: 10s
          retries: 5
    db:
        image: mysql:8.0.21
        container_name: db
        platform: linux/x86_64
        ports:
          - 3002:3306
        environment:
          - MYSQL_ROOT_PASSWORD=123456
        restart: 'always'
        healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 10s
          retries: 5